name: github-action

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.4']
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
        echo -e "#!/bin/sh\necho \"CI build\"" >> print-nixpkgs-path
        chmod 755 print-nixpkgs-path
    - name: Build
      run: env PATH=.:$PATH cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: env PATH=.:$PATH cabal test all
